# Generated by Django 4.2.1 on 2023-05-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0003_person_image_alter_person_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
